### PR TITLE
Change/remote references to Erisa/Gold

### PR DESCRIPTION
**Pull request by Erisa**

### CODE REVIEW

**Review by cleverActon0126 — APPROVED** [review]

**Comment by Erisa** [comment]
I'm going to have to live with that "remote" typo of "remove" forever now lol

**Comment by cleverActon0126** [comment]
> I'm going to have to live with that "remote" typo of "remove" forever now lol

lol I'll fix that

**Comment by Erisa** [comment]
You 

> 
> 
> > I'm going to have to live with that "remote" typo of "remove" forever now lol
> 
> lol I'll fix that

You can't its a commit haha

**Comment by cleverActon0126** [comment]
> > > I'm going to have to live with that "remote" typo of "remove" forever now lol
> > 
> > 
> > lol I'll fix that
> 
> You can't its a commit haha

oops didn't notice :WhenLifeGetsAtYou:

**Comment by cleverActon0126** [comment]
> > > > I'm going to have to live with that "remote" typo of "remove" forever now lol
> > > 
> > > 
> > > lol I'll fix that
> > 
> > 
> > You can't its a commit haha
> 
> oops didn't notice :WhenLifeGetsAtYou:

**LIVE WITH IT**

**Pull request merged**
